### ISSUE TITLE
Not suggested for the second and subsequent Hashtags in the search word

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#106]
Not suggested for the second and subsequent Hashtags in the search word.

---

SNS 検索フィールドに hashtag を入力し、空白をはさみ2番目の Hashtag を入力すると、2番目の Hashtag を対象に suggest して、2番目の Hashtag を補完してほしい。

**Comment by tkhsknsk** [comment]
@stmtstk 

Would you like to switch your suggestion library to suggest.js?

reason to switch
- Difficulty finding ways to extend the behavior of suggestions in typeahead.js.
- An example implementation of a 2-word suggestion is shown in the demo.
(ENG) http://www.enjoyxstudy.com/javascript/suggest/demo.en/demo4.html
- It doesn't support Ajax out of the box, but there are examples online.
(JPN) https://fujishinko.exblog.jp/8165048/

---

サジェストのライブラリをsuggest.jsに切り替えたいですが、よろしいでしょうか？

切り替える理由
- typeahead.jsでサジェストの動作を拡張する方法がなかなか見つからないこと
- 2ワードのサジェストの実装例がデモに載っていること
(JPN) http://www.enjoyxstudy.com/javascript/suggest/demo/demo4.html
- そのままではAjaxに対応していないが、対応例がネットに載っていること
(JPN) https://fujishinko.exblog.jp/8165048/
