### ISSUE TITLE
Completion a tag in the post textarea and the title text field.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#107]
Completion a tag in the post textarea.

---

投稿テキストエリアとタイトルテキストフィールドで Tag の補完機能を実装する。
"# + 任意の一文字入力"で、S-TIP に tags の問い合わせを実施し、候補をリストアップして、補完する。

**Comment by tkhsknsk** [comment]
Add a library to get the caret position.
http://akiroom.github.io/caretposition.js/
