### ISSUE TITLE
Cannot communicate with Slack over a proxy.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#111]
https://github.com/s-tip/stip-sns/blob/d6ca0f6053de65695904474703476cca37bb61ca/src/daemon/slack/receive.py#L96

When S-TIP generates `slack.WebClient` and `slack.RTMClient`, S-TIP does not specify a proxy argument.
We should add the proxy argument.
This value should be set like below.

```
from ctirs.models import System

proxies = System.get_request_proxies()
proxy_str = if 'https' in proxies proxies['https'] else None

slack_web_client = slack.WebClient(
        token=slack_token,
        proxy=proxies['https'])
```

---

Slack 呼び出し時に利用する `slack.WebClient` と `slack.RTMClient` 生成時に proxy 設定がないので、
proxy 配下で Slack 通信に失敗します。
proxy 引数を追加します。
Proxy の値は System から取得してください。RS の Sysmte で設定する値が取得できます。
Proxy の設定がない場合は `proxies` は空辞書が返却されます

**Comment by uchimrina** [comment]
@stmtstk 
How do I test the RTMClient?
I thought it would be displayed on the S-TIP feed screen when I write on the Slack channel, but is the procedure wrong?

It is also used in the "restart _ receive _ slack _ thread" function, so it should specify the proxy arguments as well.

---  
RTMClient のテスト方法について教えてください。
Slack のチャンネルに書込みをすると、S-TIPのFeed画面に表示されるかと思いましたが、手順が違いますか？

また、「restart_receive_slack_thread」関数の中でも使われていますので、こちらも同様にproxyの引数を指定するようにします。

**Comment by uchimrina** [comment]
> If no Proxy is set, `proxies` will return an empty dictionary.

`proxies `were returned `None` if Proxy was not set.
So I will code it accordingly.

---  
> Proxy の設定がない場合は `proxies `は空辞書が返却されます。

Proxy の設定がない場合は `proxies` は`None`が返却されました。
従って、こちらにあわせてコーディングします。

**Comment by uchimrina** [comment]
https://github.com/s-tip/stip-sns/blob/d6ca0f6053de65695904474703476cca37bb61ca/src/daemon/slack/receive.py#L62
The `start` of `RTMClient` is not done, and the status is as follows.
> `<SlackThread (Thread -1, stopped 140526673569536)>`

Can I `start` outside the proxy environment?

---  

https://github.com/s-tip/stip-sns/blob/d6ca0f6053de65695904474703476cca37bb61ca/src/daemon/slack/receive.py#L62
上記の `RTMClient` の `start` が出来ていなくて、以下の状態です。
> `<SlackThread(Thread-1, stopped 140526673569536)>`

プロキシ環境外では、`RTMClient` の `start` できているのか教えてください。
