### ISSUE TITLE
I want to support full-width space separation by suggestion.

### ISSUE THREAD

**Issue by tkhsknsk** [s-tip/stip-sns#117]
When entering multiple keywords (Space delimited) in the `suggest.js` library, I want to support full-width space separators.
It is necessary to investigate because the setting of the delimiter alone is not sufficient.

---

ライブラリ`suggest.js`で複数キーワード(スペース区切り)を入力する場合、全角スペース区切りにも対応したい。
デリミタの設定だけでは対応できないので調査する必要がある。

**Comment by tkhsknsk** [comment]
@stmtstk 
https://github.com/s-tip/stip-common/blob/master/src/static/js/suggest.js#L492

The lastIndexOf function finds the position of the delimiter to correspond to multiple keywords.
The fastest way is to modify the `suggest.js` library, is that okay?
Since it is an MIT license, I think there is no problem to modify and use it.

---

lastIndexOf関数が区切り文字の位置を見つけて複数のキーワードに対応しています。
`suggest.js`ライブラリを修正するのが一番早い方法になりますがよろしいでしょうか？
MITライセンスなので修正・利用には問題ないという認識です。

**Comment by stmtstk** [comment]
@tkhsknsk 
It is a nice idea for us.
Thanks for your investigation.

**Comment by tkhsknsk** [comment]
You have confirmed that 26 characters, such as tabs, line breaks, and white spaces, act as delimiters.
```
20:" " OK
c:"" OK
a:"
" OK
d:"
" OK
9:"	" OK
b:"" OK
a0:" " OK
1680:" " OK
180e:"᠎" OK
2000:" " OK
2001:" "  OK
2002:" "  OK
2003:" " OK
2004:" " OK
2005:" " OK
2006:" " OK
2007:" " OK
2008:" " OK
2009:" " OK
200a:" " OK
2028:" " OK
2029:" " OK
202f:" " OK
205f:" " OK
3000:"　" OK
feff:"﻿" OK
```

---

タブ、改行、ホワイトスペースなどの26文字を区切り文字として動くことを確認しました。

**Comment by tkhsknsk** [comment]
If your browser gets slow with this, you should reduce the number of characters in multiDelim.

---

今回の対応で、ブラウザの処理が重くなった場合、multiDelimの文字数を減らすべきです。
