### ISSUE TITLE
Uncaught TypeError occurs in some pages.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#127]
When an user show pages without feed page (i.e. /network/),  `Uncaught TypeError: Cannot read property 'value' of null` occurs in a javascript console.
It seems that if the page does not contain a post textarea or a title text field, this error has occured.

---

フィードページ以外のページを表示 (たとえば /network/ とか) を表示すると `Uncaught TypeError` が JavaScript Console に表示されます。
投稿のページだとエラーが発生しないので、多分、投稿 textarea や タイトル text field が存在しないときに発生するのかと思います。

**Comment by tkhsknsk** [comment]
bug fix
*Fixing a bug that causes an error when a non-existent ID other than Feed appears.

Code Refactoring
*Function handling of addEventListener
*Remove global variable sg
*Renaming the sg Variable
