### ISSUE TITLE
Confirm a behavior of change field with password fields.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#29]
According to the specification of django, values of a password field show no value.
When the password field keep a blank value and an end user submits to S-TIP, S-TIP overwrite password fields to blank value. It is not good behavior.
S-TIP should not overwrite password field values when blank value is submitted.

So we should check overwrite behaviors. If overwrite behavior exists, we should stop to overwrite a blank value.

---

Django の仕様上、パスワードフィールドに値が含まれていたとしても、変更画面には何も表示されない。

その状態で、エンドユーザが submit してしまうと、空白で上書きしてしまう。
これは、よくない挙動である。

数か所はすでに対処済であるが、漏れがあるかもしれないので、password field を表示/変更可能な画面でパスワードが空白の時に submit を行い、空白で上書きされる画面であれば、
パスワードだけは上書きしないように修正すべきである。

**Comment by ta-hiroki** [comment]
@stmtstk さん

パスワード属性の入力フォーム('Phantom Source Token'と'Splunk Password')の確認を行いました。
値が設定されている状態(表示上空白)でsubmitしてもDB上の値は空白で上書きされていませんでした。
  
実施した手順は以下
1.  S-TIP SNSにadmin権限ユーザでログインし[Account Settings]をクリック
2. DBのstip_sns_userテーブルの[phantom_auth_token]と[splunk_password]に値が設定されていないことを確認
3. S-TIP SNSで[Phantom Source Token]と[Splunk Password]に適当な値を設定し[Save]をクリック
4. DBのstip_sns_userテーブルの[phantom_auth_token]と[splunk_password]に値が設定されていることを確認
5.  S-TIP SNSで[Account Settings]をクリックし[phantom_auth_token]と[splunk_password]が空白表示されていることを確認し[Save]をクリック
6. DBのstip_sns_userテーブルの[phantom_auth_token]と[splunk_password]の値が空白で上書きされていないことを確認

**Comment by stmtstk** [comment]
Thank you!! @tkhsknsk 

Could you check also sns config page?

/management/sns_config/

Password Fields are below

- X-CSIX-CUSTID for CrowdStrikeAPI
- X-CSIX-CUSTkEY for CrowdStrikeAPI
- JIRA Password or API Token

**Comment by ta-hiroki** [comment]
@stmtstk 
> Could you check also sns config page?

Yes, sir.

**Comment by stmtstk** [comment]
Sorry, I mistake your name...

**Comment by ta-hiroki** [comment]
@stmtstk 

>- JIRA Password or API Token

Not overwrite password field values when blank value is submitted. 
(DB table: stip_sns_system, column: jira_password)


>- X-CSIX-CUSTID for CrowdStrikeAPI
>- X-CSIX-CUSTkEY for CrowdStrikeAPI

The input field is type="text" , not type="password".

**Comment by stmtstk** [comment]
@ta-hiroki 

I got it.
Thank you for investigating.
It seems that empty password value overwrite password fields.

OK.
Close this issue.
