### ISSUE TITLE
SNS Timeline shows even after the login session has timed out

### ISSUE THREAD

**Issue by rmasuoka** [s-tip/stip-sns#30]
I noticed that the SNS timeline shows even after the login session has timed out. (I know it is not a safe practice to leave the session left alone.) I believe it is better for S-TIP to erase the SNS timeline and to return to the original login page when the login session times out.

**Comment by ykoji8681** [comment]
@rmasuoka Good comment.

I found the recommendation of session expiration time in OWASP document.
https://owasp.org/www-project-cheat-sheets/cheatsheets/Session_Management_Cheat_Sheet.html

```
Common idle timeouts ranges are 2-5 minutes for high-value applications and 
15-30 minutes for low risk applications.
```

I suggest as follows in S-TIP future version: 
* The default session expiration time is 30 minutes in S-TIP
* admin user can modify the session expiration time in "Management" - "SNS config".

Any comments?

**Comment by stmtstk** [comment]
We implemented session time out on GraphView.

https://github.com/s-tip/stip-gv/blob/master/src/gv/dashboard/views.py

`request.session.set_expiry(SESSION_EXPIRY)
`

It is easy to set a session timeout.
Now, SESSION_EXPIRY is a const value (28800 secs = 8 hours).
In SNS and RS, we have not applied session.set_expiry.

So if you would like to implement session timeout.

- We must apply a session timeout on all components.
- Session timeout value can be modified by S-TIP admin role user only.

**Comment by rmasuoka** [comment]
I am afraid that you misunderstood my comment. This is a UI issue. I do get logged out automatically after a while. The problem is that I still see the SNS timeline behind the login dialog box.

**Comment by ykoji8681** [comment]
I guess this problem occurs with the following steps:

1.  Log in to S-TIP (tab-1).

2. Open another tab (tab-2) of the same S-TIP instance in the browzer.

3. Log out from S-TIP on tab-2.
4. Click some button (e.g. bell icon in SNS) in tab-1.

**Comment by ta-hiroki** [comment]
Confirmed that the problem occurs with https://github.com/s-tip/stip-sns/issues/30#issuecomment-634446109.

login _ required does not work as expected in the ajax call.
(Do not transition to the login screen)

@stmtstk
Change to the following process.
Verify the authorization in views.py and return the result in json.
Check the information of json and decide whether to transfer to the login screen.

------

https://github.com/s-tip/stip-sns/issues/30#issuecomment-634446109 の手順を確認して事象が発生することを確認できました。

ajax 処理で呼び出している views.py の関数は login_required が指定してありますが、  
想定している動作をしないようです。
(ログイン画面に遷移しない)

@stmtstk 
以下の処理に変更します。 
views.pyで認証状況を確認し、結果をjsonで返却。  
js側でjsonの情報を元にログイン画面に遷移するかどうか判断する。

**Comment by stmtstk** [comment]
Thanks @ta-hiroki .

I would like to know do we have to add a login verifiation to every login_required?

----

ありがとうございます。
これって、すべての login_required で挿入しないといけない処理なのでしょうか？

**Comment by ta-hiroki** [comment]
@stmtstk 

Modify only functions called by ajax processing.
Otherwise, no modification is necessary.

---

ajax処理により呼び出される関数のみ修正します。
それ以外は修正不要です。

**Comment by stmtstk** [comment]
@ta-hiroki 
Could you tell me which source (function) file will you modify?

---

具体的にどのファイルのどの関数を直すつもりか教えてください。

**Comment by ta-hiroki** [comment]
@stmtstk 

Modify the following two files. 
 - https://github.com/s-tip/stip-sns/blob/master/src/activities/views.py
 - https://github.com/s-tip/stip-sns/blob/master/src/activities/static/js/notifications.js

views.py modifies two functions.
("last_notifications" and "check_notifications") 
Modified Example ("last_notifications"):
```
@ajax_required
def last_notifications(request):
    if request.user.is_authenticated():
        user = request.user
        notifications = Notification.objects.filter(to_user=user,
                                                is_read=False)[:5]
        for notification in notifications:
            notification.is_read = True
            notification.save()
        notifications = get_template('activities/last_notifications.html').render({'notifications': notifications},request)
        results = json.dumps(
                {
                    'authenticated': True ,
                    'notifications': notifications
                }
        )
    else:
        results = json.dumps({ 'authenticated': False })
    return HttpResponse(results, content_type='application/json')
```

  1. Delete "@login_required".
  2. Check the authentication with "request.user.is_authenticated()" and return the result with json.

notifications.js modifies two functions.
("$("#notifications").click(function ()" and "function check_notifications()")
Modified Example ("$("#notifications").click(function ()"):
```
        success: function (data) {
          console.log(data)
          if (data.authenticated) {
            $(".popover-content").html(data.notifications);
          }
          else{
            window.location.href = '/login';
          }
        }
```
1. Check the information of json and decide whether to transfer to the login screen.

**Comment by stmtstk** [comment]
@ta-hiroki 

We must concern any other cases.
For example, when an user losts a login session and click comment link instead of a notification bell, same issue occurs.
We must care about all ajax_required calls.

Do we have to consider other approches?

---

今回のベルクリック以外でも、セションが切れている状態で コメントリンクをクリックしても同じことが起きます。ヘッダの management では起きないので、ajax 処理をしているところで対処をしなくてはいけません。
すべての ajax_required にこの処理をするひつようがあるのか、もしくは別の方法があればそちらを検討したほうがいいかもしれません。
django で ajax 使うときにセションが切れた時に最適な方法があるか、internet に他の例があるか調べるなどそちらの側面から検討してもらえませんか？

**Comment by ta-hiroki** [comment]
@stmtstk 

How about the following method?
Changes are required for HTML and js.

1. Tag the login page.

2. In the case of session timeout, the login page HTML information is returned from the server.
The information of the tag is used to decide whether to transfer to the login page.

------

以下の方法はいかがでしょうか?
HTMLとjsに変更が必要です。

1. ログインページにタグを設置する。
2. セッションタイムアウトの場合はサーバからログインページのHTML情報が返却される。
タグの情報でログインページに遷移するか判断する。

**Comment by ta-hiroki** [comment]
@stmtstk

How about the following method?
Changes are required for HTML and js.

1. Add a Tag to login page.
Example: Add a Tag to stip-common/src/templates/cover.html 
```
  <input type="hidden" name="TIMEOUT" value="1"/>`
```


2. In the case of session timeout, the login page HTML information is returned from the server.
The information of the tag is used to decide whether to transfer to the login page.
Example: Add function to stip-sns/src/activities/static/js/notifications.js
```
~
      $.ajax({
        url: '/notifications/last/',
        beforeSend: function () {
          $(".popover-content").html("<div style='text-align:center'><img src='/static/img/loading.gif'></div>");
          $("#notifications").removeClass("new-notifications");
        },
        success: function (data) {
          check_auth(data)
          console.log(data)
~
  function check_auth(data) {
    var parser = new DOMParser();
    var parse_data = parser.parseFromString(data, "text/html");
    var data_value = parse_data.getElementsByName('TIMEOUT')[0].value;
    if(data_value == "1"){
      window.location.href = '/login';
    };
  };
~~
```

-----

以下の方法はいかがでしょうか?
HTMLとjsに変更が必要です。

1. ログインページにタグを設置する。
2. セッションタイムアウトの場合はサーバからログインページのHTML情報が返却される。
jsでタグの情報を確認しログインページに遷移するか判断する。

**Comment by stmtstk** [comment]
I would like to recommend to use a ajaxComplete handler.

https://qiita.com/_ka_wa_chi_/items/6e93e190cd661d6cf33b

If a timeout has occured, django return redirect to login page response.

https://awesome-linus.com/2019/04/03/django-return-redirect-and-redirect-js/

We should also reffer this page.
https://ja.wikipedia.org/wiki/XMLHttpRequest

---

その方法だと ajax の箇所すべてを修正する必要がでてきます。
ちょっと調べたところ、ajaxCompete で ajax request 完了後のハンドラが設定できます。

なので、以下のような修正指針はどうでしょう？
まず、session timeout が発生したときに login page に redirect するように views.py の方を修正します。

ajaxComplete の中で第二引数の xhr.status が 4 (Done) で  redirect であることを検知したら javascript の windows.location.href で views.py の中で設定された redirect 先のページ、すなわちログインページに遷移する。

ちょっと検証してもらえませんか？

**Comment by ta-hiroki** [comment]
@stmtstk 

https://github.com/s-tip/stip-sns/issues/30#issuecomment-645141511 A has been verified.
(Successfully confirmed that transition to the login page)
I want to use js as a common function.
Is there an appropriate file?

-----

提示して頂いた内容を検証しました。
（ログインページに遷移できることを確認できました）
jsに追記する必要がある処理は共通して利用できる関数としたいです。
処理の追記に適切なファイルがあれば教えていだけないでしょうか?

**Comment by stmtstk** [comment]
ALL SNS pages include the base.html block in stip-common (https://github.com/s-tip/stip-common/blob/master/src/templates/base.html).

In base.html, we should add another script tag after bootcamp.js.

```
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootcamp.js' %}"></script>
    <script src="{% static 'js/stip_ajax.js' %}"></script>
```

Add the stip_ajax.js in https://github.com/s-tip/stip-sns/tree/master/src/core/static/js.

We should write the ajaxComplete Handler in stip_ajax.js.

---


すべての SNS コンテンツは stip-common で定義の base.html を含んでいます。
base.html 内の script タグを一つ追加しましょう。stip_ajax.js くらいの名前で。
stip_ajax.js は stip-common の src/core/static/js に格納して、
stip_ajax.js に ajaxComplete Handeler を追加しましょう。

テストに当たっては、 python manage.py collectstatic を忘れずに。

**Comment by ta-hiroki** [comment]
I added a issue because I need to change the stip-common repository.
Added issue: https://github.com/s-tip/stip-common/issues/27

**Comment by ta-hiroki** [comment]
I implemented the process using ajax_required instead of https://github.com/s-tip/stip-sns/issues/30#issuecomment-645141511.   
(In https://github.com/s-tip/stip-sns/issues/30#issuecomment-645141511, some processes did not work as expected.)

**Comment by stmtstk** [comment]
Thanks @ta-hiroki!!

I checked your works.
I have approved and merged your pull requests into release_11.

You can close this issue.
