### ISSUE TITLE
Modifies the result screen of the search function

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-sns#31]
検索結果画面に以下の修正加える。

<修正内容>
- 検索結果画面は通常のタイムライン画面と同様としマッチした投稿のみを表示する。 ( 新規投稿ボタン ( [New] ) も表示 )
- 検索ワードを画面上に表示し検索結果の画面だと明示的にする。
- 検索対象は投稿の「Title」「Content」「Username ( Screnn nameも含む ) 」とする。
- 検索ワードが半角スペースで区切られている場合、両方の単語を含む投稿を検索対象とする。

**Comment by ta-hiroki** [comment]
@stmtstk さん

２点質問があります。

- [Search] (検索条件にマッチした投稿のみが表示されている状態) > [New] (新規投稿) を実行した場合、
どのような挙動がよいでしょうか?
 ( 新規投稿が検索条件にマッチする場合のみ検索結果と合わせて表示、
マッチしない場合は検索結果画面には表示しないという挙動で問題ないでしょうか?)

- 検索結果画面のタイムラインは更新をした方がよいのでしょうか?
( 別ユーザが投稿を実行した際にタイムラインに[New post]で投稿が反映されると思いますが、
検索結果画面のタイムラインでも同様の処理は必要でしょうか? )　
 ---
I have two questions.
- If [Search] (Only matching posts are shown) > [New] (New Post), what is the correct behavior?
- Is it necessary to update the timeline on the search result screen?

**Comment by stmtstk** [comment]
- Please implement with the behavior as suggested by you
- If a timeline is modified while showing a search result, we would like to 'NOT' modified timeline.

---

- [Search] > [New] はご提案通りの挙動で実装お願いします
- 検索結果のタイムラインは更新しないという挙動にしたいのですが、従来のタイムラインと挙動が異なるため、どれくらい変更に時間がかかるかわからないです。簡単にできるようなら更新しない方向で実装をお願いします。

**Comment by rmasuoka** [comment]
When I added a FireEye blog, the UI get messed up after CTI Element Extractor. Please see attached screenshot.
![S-TIP-UI](https://user-images.githubusercontent.com/36691131/74908400-199e7a80-53f9-11ea-8b3c-14e1aa627347.png)

**Comment by rmasuoka** [comment]
I think it should show some message like "Username and Password do not match" when the login attempt fails.

**Comment by stmtstk** [comment]
@rmasuoka 
I will raise another issue about the login message.

**Comment by rmasuoka** [comment]
When I searched for APT29 after adding the FireEye blog and it showed the FireEye blog in the search result and it is okay. However, when I added the next post "APT29" in the search result page, it did not show the post "APT29." I thought that the correct behavior is that the search result page includes the new post if it includes the search word. (The new post was shown in the search page along with the blog when I searched for APT29 again.)

**Comment by rmasuoka** [comment]
The search result page shows "More feeds" even though there is no more feeds. I think "More feeds" should appear only when there are more feeds, which cannot be shown.

**Comment by ta-hiroki** [comment]
Fixed bug in https://github.com/s-tip/stip-sns/issues/31#issuecomment-588639158 and https://github.com/s-tip/stip-sns/issues/31#issuecomment-588646589 .

**Comment by ta-hiroki** [comment]
@rmasuoka @stmtstk 

Language setting changes the word ("Search word") on the search results screen. 

| Language | Word |
| ------------- | ------------- |
| en |  Search |
| es | Buscar | 
 | fr |  Chercher | 
 | ja |  検索 | 
 | pt_BR |  Procurar | 
 | zh_CN |  搜索  |

**Comment by ta-hiroki** [comment]
@stmtstk 

Another problem is that you cannot set the Language to "Protuguese" and "Chinese".

![image](https://user-images.githubusercontent.com/50686125/74997224-faefc080-5498-11ea-85c8-729bc66bceb8.png)

**Comment by stmtstk** [comment]
I confirmed the behavior. It is bug.
I will tackle this bug as another issue.

Thank you for reporting.
