### ISSUE TITLE
Allow users to delete their comments posted on SNS

### ISSUE THREAD

**Issue by tkhsknsk** [s-tip/stip-sns#33]
When you click the x button, the action disappears.
However, reloading the feeds screen will restore them.
There is some cache left.

**Comment by tkhsknsk** [comment]
@stmtstk 

I found a function to remove using the package ID. Which method is better?

- Remove Package ID via API `/api/v1/stix_files_package_id/<package_id>`?
- Do I call the `delete_stix_file_package_id_document_info` method from SNS to delete the package ID?

https://github.com/s-tip/stip-rs/blob/master/src/ctirs/api/v1/package_id/views.py#L9

---

パッケージIDを削除する関数を見つけました。  
2つの方法が考えられますがどちらがよろしいのでしょうか？

- API`/api/v1/stix_files_package_id/<package_id>`経由で削除する
- `delete_stix_file_package_id_document_info` メソッドを利用して削除する

**Comment by stmtstk** [comment]
I think we should call rest api `/api/v1/stix_files_package_id/<package_id>`

**Comment by tkhsknsk** [comment]
I understand. Take advantage of the REST API.

S-TIP's PackageID is slightly different, so please let me know the specification.

STIP-SNS used two hyphens and STIP-RS REST API required colons.
Is it converted somewhere?

Package ID displayed on STIP-SNS
s-tip`--`Package-xxxxxx

PackageID to display in the list of STIP-RS.
PackageID when retrieving/deleting with REST API
s-tip`:`Package-xxxxxx

I asked because I couldn't find a process to replace a colon with a hyphen.

---

REST APIを使う方向で承知しました。
S-TIPのPackage IDがSNSとRSで多少異なるのでこの扱いについて教えて下さい。

STIP-SNSのPackage ID
s-tip`--`Package-xxxxxx

STIP-RSのPackage ID
s-tip`:`Package-xxxxxx

--と:を置換する処理が見つからなかったので教えて下さい。よろしくお願いします。

**Comment by stmtstk** [comment]
from `:` to `--` 
SNS: /src/feeds/feeds_filter.py
```
def get_accordion_pk(v):
    return v.replace(':', '--')

```
RS: /ctirs/models/sns/feeds/rs.py

```
def covert_package_id_to_filename(package_id):
def convert_filename_to_package_id(filename):

```
S-TIP uses Package ID (stip-:...) as an id attribution in HTML tag.
However, a value including colon is not allowed to use as a HTML attribute value.
So S-TIP convert `:` to `--`

---

Package ID をHTML の attribute の値に使おうと思ったのですが、`:` が使えないため、
`--` に変換しています。

変換場所は rs にありました。 SNS にもありますが、同じロジックですので使いやすいほうを使ってください。

**Comment by tkhsknsk** [comment]
Thank you.
Use the following function to convert.
`def convert_filename_to_package_id(filename):`

---
ありがとうございます。見逃してました。
この関数を用いて実装します。
