### ISSUE TITLE
Fix to set an appropriate ciritcal_infrastructure value in a x_stip_sns_author property.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-sns#47]

**Comment by ta-hiroki** [comment]
@stmtstk 

If a new user is added, the affiliation value is also NULL.
Is there any problem with the same way of dealing?

----

新規ユーザを追加した場合、affiliation の値も NULL となります。  
同様の対応方法で問題ないでしょうか?  

新規ユーザ (hiroki) を追加直後のDBの情報です。

| username      | ci                                     | affiliation |
| ------------- | ------------- | ------------- |
| admin         | Information and Communication Services |             |
| na            | NULL                                   |             |
| anonymous     | NULL                                   |             |
| gv_concierge  | NULL                                   |             |
| alienvaultotx | NULL                                   |             |
| misp          | NULL                                   |             |
| slack         | NULL                                   |             |
| hiroki        | NULL                                   | NULL        |

**Comment by stmtstk** [comment]
Thanks for your reporting.

You are right. We should do same for affiliation as for critical_infrastructure.

---


```
            "x_stip_sns_author": {
                "affiliation": null,
                "country_code": "",
                "critical_infrastructure": null,
                "region_code": "",
                "screen_name": "user1",
                "username": "user1"
            },

```
---


報告ありがとうございます。
ご提案通り、 affiliation でも同様の処理が必要ですね。
この issue でまとめて対応してもらえませんか？

**Comment by stmtstk** [comment]
Thank you for your co-operation.
