### ISSUE TITLE
Fix a decoding issue when a sighting object is created.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#50]

**Comment by ykoji8681** [comment]
Thanks, @stmtstk . 
I would appreciate it if you add the situation when this error occurs.

**Comment by ykoji8681** [comment]
I remembered the situation. 

When I post with Japanese characters and click Sightings button, following error occurred:

```
'ascii' codec can't decode byte 0xe3 in position xxxx: ordinal not in range(128)
```

**Comment by stmtstk** [comment]
We should know where below messages appears.

```
'ascii' codec can't decode byte 0xe3 in position xxxx: ordinal not in range(128)
```

`open('rb')` or `fp.read()` or `stix2.parse` or anywhere else.
