### ISSUE TITLE
Add the MFA setting screen.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-sns#62]
Enable MFA settings for each account in /settings/password.

---

/settings/password で各アカウントの MFA 設定を設定できるようにする。

**Comment by tkhsknsk** [comment]
@stmtstk 

QR code image file can be sent by BytesIO without saving to HDD.
I plan to use Ajax to encode the image file in base 64 and return it as a JSON value.

It is necessary to confirm whether it is registered correctly with the authentication code.
If you don't keep the value of secet, you can't check it.

We have two plans. Please tell me which is better.

1. Check the authorization code and POST the secet together.
Benefits
  There are few modifications.
Demerit
  There is a risk of registering by changing secet in a browser.

1. Create a temporary registration column in the DB.
Benefits
  Be secured by the security
Demerit
  One column is added to the DB

-----

QRコードの画像ファイルはBytesIOでHDDに保存せずにデータを送ることが出来ます。
Ajaxで画像ファイルをbase64でエンコードした上でJSON形式の値にして返そうと考えてます。

2FAの登録する際、認証コードで正しく登録されているかの確認でsecetの値をサーバ側で保持していないと
認証コードがわからないという問題があります。

プランが２つあります。どちらが良いかアドバイスをください。

1. 認証コードを送信するときに一緒にsecetもPOSTします。
メリット
  修正が少なく済む
デメリット
  セキュリティ的に不安。

1. DBに仮登録の列を追加します
メリット
  セキュリテイがより高まる
デメリット
  DBにカラムを１つ追加する必要がある

**Comment by stmtstk** [comment]
@tkhsknsk 

We should choice the plan 1.
And I would like to ask you to display the secret key with QR code.

"If you can not scan QR code, plese enter key manual. <secret value>"

It seems to be a common QR code setting.

---

1 のプランにしましょう。
そして、 QR コードの下に、「QR コードが読み込めない場合は、2FA アプリケーションに以下の文字コードを入力してください」といった旨の文とともに secret  の値を表示してください。
それが一般的な QR コードを使った 2FA の設定画面のようです。

**Comment by stmtstk** [comment]
@tkhsknsk 

I would like to choose case 2.
However, instead of using DB, use django session.

https://djangoproject.jp/doc/ja/1.0/topics/http/sessions.html

When moving to a 2FA setting page, set session value below.

```
request.session['secret_key'] = 'secret_value'
```

An user subit an authentication code without `secret_value`.

S-TIP receives a request, we can get secret_value below.

```
secret_value = request.session['secret_key']
```
---

2つ目のプランで行きたいのですが、 DB を使うのではなく Django のセションを使うのはいかがでしょうか？

上記のコードのように、 2FA 設定画面表示時に request.session に secret_value を送る。
ユーザが Authentication code を入力して submit する時に secret_value は「送らない」ようにする。
ただし、セションから secret_value は復元できる。

この方法で試してもらえないでしょうか？

**Comment by tkhsknsk** [comment]
Thank you.
We've seen it work well with sessions.

**Comment by tkhsknsk** [comment]
@stmtstk 
Is the registration screen for TOTP authentication a modal image?
It was not written that modal was used in the prior explanation, so I would like to confirm.
Please give me instructions if you have any requests.

-----

TOTP認証の登録画面は、モーダルを使うイメージでよろしいでしょうか？
事前説明でモーダルを使うと書いていなかったので確認です。
要望がありましたら指示をよろしくお願いします。
![2020-08-12_14-36-10_Account Settings - Google Chrome](https://user-images.githubusercontent.com/50690271/89985511-24561000-dcb6-11ea-8044-f298015a9a1c.png)

**Comment by stmtstk** [comment]
A modal dialog is very good.
Please change sentence.

> Input authentication code (6 digits)

An user may confuse to input secret_key code instead of 6 digits.

---

modal dialog box いいですね。これで行きましょう。
あと、文字列ですが、 "(6 digits)" と明示しておきましょう。
もしかしたら secret_keys を入力してしまうかもしれないので。

**Comment by tkhsknsk** [comment]
Closed as approved.
