### ISSUE TITLE
Save hashtags into a labels property when an user posts with them.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#87]
When a user posts into SNS, S-TIP creates a `report` and `x-stip-sns` object.
Two objects can have a `labels` property as common property.
When a user posts it with hashtags, set this hashtags into a `lebels` property.

Below is create a `x-stip-sns` object.

https://github.com/s-tip/stip-sns/blob/d6ca0f6053de65695904474703476cca37bb61ca/src/feeds/feed_stix2.py#L368

We should add argument like this.

```
labels = ['hasttag1', 'hashtag2']
```

It create report objects. 

https://github.com/s-tip/stip-sns/blob/d6ca0f6053de65695904474703476cca37bb61ca/src/feeds/feed_stix2.py#L389

It creates report objects. 

---

S-TIP 投稿時に `x-stip-sns` と `report` オブジェクトが作成されます。
それぞれに共通プロパティとして `labels` property があります。
もし Hashtags 付きの投稿があれば、それを分解して、 `labels` property に追加します (hashtag がない場合は特に動作の変更なありません).

labels の追加方法は上記の URL で Object を作成するときの引数に `labels=[...]` を追加すれば大丈夫です。

**Comment by ta-hiroki** [comment]
@stmtstk 

Is the recognition of the hashtag extracted from the post correct?

- Starts with #
- Does not contain the symbol
- Half-width space before and after the hashtag (Ignore at beginning and end of post)

ex)
1) #aaaa bbbb #cccc -> extract #aaaa and #cccc

2) #aaaa -> extract #aaaa

3) aaaa #bb * bb -> no extraction

4) aaaa #bbbccccc -> extract #bbbbcccc

---

投稿から抽出するハッシュタグの認識は正しいでしょうか? 

- `#` で始まる
- 記号を含まない
- ハッシュタグの前後は半角スペース（投稿の最初と最後の場合は無視）

例) 

#aaaa bbbb #cccc -> #aaaa と #cccc を抽出

#aaaa -> #aaaa を抽出

aaaa #bb*bb -> 抽出なし

aaaa #bbbbcccc -> #bbbbccc を抽出

**Comment by stmtstk** [comment]
@ta-hiroki 

I would like to be same as the hashtag rule on Twitter

---

Twitter と同じルールにしたいと思います。
Twitter で Hashtag になるかどうか調査しながら進めてください

**Comment by ta-hiroki** [comment]
@stmtstk 

There was not much [official information](https://help.twitter.com/ja/using-twitter/how-to-use-hashtags), but I would like to make the following specification with the content I actually used.  

- Starts with #
- Does not contain the symbol, separate if a symbol is used (Can be used '_')
- Half-width space before and after the hashtag (Ignore at beginning and end of post)
- Do not use a hash tag for numbers and `_` only.
---


[公式の情報](https://help.twitter.com/ja/using-twitter/how-to-use-hashtags)は少なかったの実際に利用してみた内容と合わせて以下の仕様にしようと思います。

- `#` で始まる
- 記号を含まず、利用されている場合そこで区切る ( `_` は利用可能)
- ハッシュタグの前後は半角スペース（投稿の最初と最後の場合は無視）
- 数字・ `_` のみ場合はハッシュタグとしない

**Comment by stmtstk** [comment]
Thanks, @ta-hiroki .

We would like to support hashtags with Japanese Characters. like #ああああ.
Twitter supports those hashtags.

**Comment by uchimrina** [comment]
Specification change  
We no longer need to store hashtags in the `x-stip-sns` object, so we'll just add the common property `labels `to the `report `object.  

---  
仕様変更
`x-stip-sns` オブジェクトには hashtags を格納する必要がなくなったので、`report ` オブジェクトだけ共通プロパティ `labels `を追加します。
