### ISSUE TITLE
When a user input hashtags in a search field, S-TIP recommends hashtags.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#88]
In SNS feeds view, when a user fills hashtags in a search field, S-TIP displays a pulldown menu with hashtags which S-TIP recommends.

We will use [Typeahead.js](https://github.com/twitter/typeahead.js/) for this function.

**Comment by tkhsknsk** [comment]
@stmtstk 

We need to make detailed specifications, so please let me check.

1. I want to set the number of candidates to submit.
 I'd like to decide up to how many cases.
 When viewing the S-TIP in full screen on a 1920 x 1080 screen,
Displays from top to center for 10 items and from top to bottom for 20 items.
 It may look bad, but you can increase the number of suggestions by narrowing the height of the suggestions with CSS.

1. order of suggestion
 When the maximum number of suggestions is exceeded, only the first part is displayed.
 Please let me know if you have any preference such as descending order of strings.
 We don't know how to set it up yet, but we will investigate.

---
細かい仕様を詰めていく必要があり、確認させてください。  

1.サジェストする候補数を設定したい。最大何件まで決めさせてください。
  1920x1080の画面をフルスクリーンでS-TIPを表示したときに、
  10件で上から中央まで表示し、20件で上から下まで表示します。
  見栄えが悪くなるかもしれませんが、CSSでサジェストの高さを狭くさせて件数を増やせます。  

2.サジェストする順序
  最大のサジェスト件数を超えた場合先頭の部分しか表示しません。。
  文字列の降順など、希望がありましたら教えて下さい。
  設定方法はまだわかっていませんが、調査します。

**Comment by stmtstk** [comment]
@tkhsknsk 

Thanks for your awareness.

1. Max to 5 cases
2. Alphabet ascending order

---

1. まずは 5 件を上限としましょう。見栄えについては (フォントサイズなど) は後で相談させてください
2. 辞書昇順でいいと思います

**Comment by tkhsknsk** [comment]
@stmtstk 

Thank you. I forgot one more thing.

The time when the suggestion starts
For example, do you want the specification to start working in the second character including the hashtag `# t`?

---

ありがとうございます。あと1つ忘れていました。

サジェストが始まるタイミングは
例えば、`#t`ハッシュタグを含めて2文字目で動作し始める仕様でよろしいでしょうか？

**Comment by stmtstk** [comment]
@tkhsknsk 

It is a good idea.
I would like to recommend to define a constant value of a search start index easily.

---

まずはその線で二文字目からにしましょう。
ただ、タグが多くなって、`#t` のタイミングでタグが多くなったら、
検索開始を 3 文字目からとすることも想定して、検索開始位置の定数をわかりやすい場所に記載してもらえますか？

**Comment by tkhsknsk** [comment]
All right. Make it easy to change.
